/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DiamondProxyTest } from "./DiamondProxyTest";

export class DiamondProxyTestFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DiamondProxyTest> {
    return super.deploy(overrides || {}) as Promise<DiamondProxyTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DiamondProxyTest {
    return super.attach(address) as DiamondProxyTest;
  }
  connect(signer: Signer): DiamondProxyTestFactory {
    return super.connect(signer) as DiamondProxyTestFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DiamondProxyTest {
    return new Contract(address, _abi, signerOrProvider) as DiamondProxyTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_freeze",
        type: "bool",
      },
    ],
    name: "setFreezability",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x0000008003000039000000400030043f000000000301001900000060033002700000000d033001970000000102200190000000240000c13d000000040230008c0000002c0000413d000000000201043b0000000f02200197000000100220009c0000002c0000c13d0000000002000416000000000202004b0000002c0000c13d000000040230008a000000200220008c0000002c0000413d0000000401100370000000000101043b000000000201004b0000000002000019000000010200c039000000000221004b0000002c0000c13d0000001102000041000000000302041a000001000400008a000000000343016f000000000113019f000000000012041b0000001201000041000000800010043f00000013010000410000002f0001042e0000000001000416000000000101004b0000002c0000c13d0000002001000039000001000010044300000120000004430000000e010000410000002f0001042e000000000100001900000030000104300000002e000004320000002f0001042e000000300001043000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000200000000000000000000000000000040000001000000000000000000ffffffff00000000000000000000000000000000000000000000000000000000bf52956900000000000000000000000000000000000000000000000000000000c8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131e33774e659306e47509050e97cb651e731180a42d458212294d30751925c551a2000000000000000000000000000000000000002000000080000000000000000084b8737127886ce4baf7c33bb18c6b06ebc7a3e5d83b3623706f3a600ba95178";
