/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DiamondUpgradeInit3Interface extends ethers.utils.Interface {
  functions: {
    "upgrade(uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "upgrade",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {};
}

export class DiamondUpgradeInit3 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DiamondUpgradeInit3Interface;

  functions: {
    upgrade(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "upgrade(uint256,address,address)"(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  upgrade(
    _priorityTxMaxGasLimit: BigNumberish,
    _allowList: string,
    _verifier: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "upgrade(uint256,address,address)"(
    _priorityTxMaxGasLimit: BigNumberish,
    _allowList: string,
    _verifier: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    upgrade(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "upgrade(uint256,address,address)"(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    upgrade(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "upgrade(uint256,address,address)"(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    upgrade(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "upgrade(uint256,address,address)"(
      _priorityTxMaxGasLimit: BigNumberish,
      _allowList: string,
      _verifier: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
