/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL1BridgeLegacy } from "./IL1BridgeLegacy";

export class IL1BridgeLegacyFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1BridgeLegacy {
    return new Contract(address, _abi, signerOrProvider) as IL1BridgeLegacy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_l2Receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "_l1Token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_l2TxGasLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_l2TxGasPerPubdataByte",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];
