/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2ERC20Bridge } from "./IL2ERC20Bridge";

export class IL2ERC20BridgeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2ERC20Bridge {
    return new Contract(address, _abi, signerOrProvider) as IL2ERC20Bridge;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_l1Bridge",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_l2TokenProxyBytecodeHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_governor",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
