/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IL2WethBridge } from "./IL2WethBridge";

export class IL2WethBridgeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2WethBridge {
    return new Contract(address, _abi, signerOrProvider) as IL2WethBridge;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_l1Bridge",
        type: "address",
      },
      {
        internalType: "address",
        name: "_l1WethAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_l2WethAddress",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
