/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IOldContractDeployer } from "./IOldContractDeployer";

export class IOldContractDeployerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOldContractDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOldContractDeployer;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "bytecodeHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "newAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "input",
            type: "bytes",
          },
        ],
        internalType: "struct IOldContractDeployer.ForceDeployment[]",
        name: "_deployParams",
        type: "tuple[]",
      },
    ],
    name: "forceDeployOnAddresses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
