/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockExecutorFacetInterface extends ethers.utils.Interface {
  functions: {
    "saveL2LogsRootHash(uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "saveL2LogsRootHash",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "saveL2LogsRootHash",
    data: BytesLike
  ): Result;

  events: {};
}

export class MockExecutorFacet extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockExecutorFacetInterface;

  functions: {
    saveL2LogsRootHash(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "saveL2LogsRootHash(uint256,bytes32)"(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  saveL2LogsRootHash(
    _batchNumber: BigNumberish,
    _l2LogsTreeRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "saveL2LogsRootHash(uint256,bytes32)"(
    _batchNumber: BigNumberish,
    _l2LogsTreeRoot: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    saveL2LogsRootHash(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "saveL2LogsRootHash(uint256,bytes32)"(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    saveL2LogsRootHash(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "saveL2LogsRootHash(uint256,bytes32)"(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    saveL2LogsRootHash(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "saveL2LogsRootHash(uint256,bytes32)"(
      _batchNumber: BigNumberish,
      _l2LogsTreeRoot: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
