/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ReenterGovernanceInterface extends ethers.utils.Interface {
  functions: {
    "initialize(address,tuple,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class ReenterGovernance extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ReenterGovernanceInterface;

  functions: {
    initialize(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,(tuple[],bytes32,bytes32),uint8)"(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  initialize(
    _governance: string,
    _op: {
      calls: { target: string; value: BigNumberish; data: BytesLike }[];
      predecessor: BytesLike;
      salt: BytesLike;
    },
    _functionToCall: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,(tuple[],bytes32,bytes32),uint8)"(
    _governance: string,
    _op: {
      calls: { target: string; value: BigNumberish; data: BytesLike }[];
      predecessor: BytesLike;
      salt: BytesLike;
    },
    _functionToCall: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,(tuple[],bytes32,bytes32),uint8)"(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,(tuple[],bytes32,bytes32),uint8)"(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,(tuple[],bytes32,bytes32),uint8)"(
      _governance: string,
      _op: {
        calls: { target: string; value: BigNumberish; data: BytesLike }[];
        predecessor: BytesLike;
        salt: BytesLike;
      },
      _functionToCall: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
