/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface VerifierRecursiveTestInterface extends ethers.utils.Interface {
  functions: {
    "verificationKeyHash()": FunctionFragment;
    "verify(uint256[],uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "verificationKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish[], BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "verificationKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class VerifierRecursiveTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: VerifierRecursiveTestInterface;

  functions: {
    verificationKeyHash(overrides?: CallOverrides): Promise<{
      vkHash: string;
      0: string;
    }>;

    "verificationKeyHash()"(overrides?: CallOverrides): Promise<{
      vkHash: string;
      0: string;
    }>;

    verify(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "verify(uint256[],uint256[],uint256[])"(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  verificationKeyHash(overrides?: CallOverrides): Promise<string>;

  "verificationKeyHash()"(overrides?: CallOverrides): Promise<string>;

  verify(
    arg0: BigNumberish[],
    arg1: BigNumberish[],
    arg2: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verify(uint256[],uint256[],uint256[])"(
    arg0: BigNumberish[],
    arg1: BigNumberish[],
    arg2: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    verificationKeyHash(overrides?: CallOverrides): Promise<string>;

    "verificationKeyHash()"(overrides?: CallOverrides): Promise<string>;

    verify(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verify(uint256[],uint256[],uint256[])"(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verificationKeyHash(overrides?: CallOverrides): Promise<BigNumber>;

    "verificationKeyHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(uint256[],uint256[],uint256[])"(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verificationKeyHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verificationKeyHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(uint256[],uint256[],uint256[])"(
      arg0: BigNumberish[],
      arg1: BigNumberish[],
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
